### PR TITLE
Beta UniFiNetworkApplication 7.2.87 Fry-Kun

### PR DESCRIPTION
**Pull request by tong2x**
Using User: Fry-kun's code for removing all mongdoDB except latest (Mongodb42)

beta UniFiNetworkApplication 7.2.87
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-2-87/29245b66-dcf2-4832-bd53-69e7c7d9929f)
Install command: fetch -o - https://tinyurl.com/y294dxxe | sh -s

beta UniFiNetworkApplication 7.2.85
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-2-85/3cfaeb66-66c0-4c22-9837-a7ed7442ae89)
Install command: fetch -o - https://tinyurl.com/4rz8ycwz | sh -s

RC UniFiNetworkApplication 7.1.66
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-1-66/cf1208d2-3898-418c-b841-699e7b773fd4)
Install command: fetch -o - https://tinyurl.com/2p857pdd | sh -s

Official UniFiNetworkApplication 7.1.65
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-1-65/ae9da509-812f-4351-8676-2e04e87d7224)
Install command: fetch -o - https://tinyurl.com/2s3hkzpa | sh -s

Official UniFiNetworkApplication 7.1.61
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-1-61/37500b1e-8f27-457b-a091-eedc70f9a528)
Install command: fetch -o - https://tinyurl.com/5n6zcybj | sh -s

Beta UniFiNetworkApplication 7.1.60
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-1-60/d8242d3c-a3a7-4997-84c9-2a96d0679a5c)
Install command: fetch -o - https://tinyurl.com/44ux65t9 | sh -s

Beta UniFiNetworkApplication 7.1.59
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-1-59/b4940216-fa4e-45ec-8427-8cd0a4383f1e)
Install command: fetch -o - https://tinyurl.com/tpty7fte | sh -s

Beta UniFiNetworkApplication 7.1.55
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-1-55/0b04846e-4f6b-44a3-b70e-ec9a38c3b811)
Install command: fetch -o - https://tinyurl.com/3ca6x72x | sh -s

Official UniFiNetworkApplication 7.0.23
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-0-23/f1b404b4-f595-4346-aaa1-df6941e35525)
Install command: fetch -o - https://tinyurl.com/45v7xh6w | sh -s

Beta UniFiNetworkApplication 7.0.22
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-0-22/dc707272-c726-4935-9d68-c5c50665b970)
Install command: fetch -o - https://tinyurl.com/yw7mz3ak | sh -s

Beta UniFiNetworkApplication 7.0.18
Install command: fetch -o - https://tinyurl.com/yeumkctm | sh -s

install at your own risk, back up your DB first

Was having problems editing Fry-Kun pull so created this pull to use the latest Unifi beta build with his added mongodb code

### CODE REVIEW

**Comment by tong2x** [comment]
works great for one of my device that is not installing mongoDB42

**Comment by tong2x** [comment]
updated to Beta/Official UniFiNetworkApplication 7.0.22 Fry-Kun

**Review by slmingol — APPROVED** [review]

**Comment by slmingol** [comment]
Tested out 7.0.23, worked fine on PFSense 2.5.0

**Review by slmingol — APPROVED** [review]

**Comment by tong2x** [comment]
_a usr/local/UniFi/data/backup/autobackup/autobackup_7.1.61_20220430_1600_1651334400135.unf
Mounting new filesystems... done.
Removing discontinued packages...
Usage: pkg lock [-lqy] [-a|[-Cgix] <pkg-name>]
       pkg lock --has-locked-packages
       pkg unlock [-lqy] [-a|[-Cgix] <pkg-name>]
For more information see 'pkg help lock'.
Usage: pkg delete [-DfnqRy] [-Cgix] <pkg-name> ...
       pkg delete [-Dnqy] -a

For more information see 'pkg help delete'.
 done.
Installing required packages..._

**Review by ReinaldoFeitosa — APPROVED** [review]

**Comment by tong2x** [comment]
fix for issue #287 

original code
`env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.txz`

replaced to
`env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg add -f ${FREEBSD_PACKAGE_URL}${pkgname}-${pkgvers}.pkg`

**Comment by tong2x** [comment]
closing, will not update
follow #292

**Pull request closed without merging**
