### PR TITLE
Beta UniFi Network Application 7.4.149

### PR DESCRIPTION
**Pull request by tong2x**
beta UniFi Network Application 7.4.149
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-4-149/85862a9d-7fb3-4d08-8db4-d66cd71d920e)
Install command: fetch -o - https://tinyurl.com/2p9fccf7 | sh -s
note: issue with the ff, seems to be issue with DB?
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/usr/local/UniFi/lib/spring-core-5.3.18.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils

beta UniFi Network Application 7.4.146
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-4-146/d6c413c2-eed6-4b20-91ae-f1cc7655d840)
Install command: fetch -o - https://tinyurl.com/mr2y2xy4 | sh -s

beta UniFi Network Application 7.4.145
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-4-145/436a20e1-261b-4e1a-90df-b6429f2a3fd1)
Install command: fetch -o - https://tinyurl.com/ycyx34km | sh -s

beta UniFi Network Application 7.4.144
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-4-144/196e40da-5eb4-45a3-9c32-f3e3a95258f1)
Install command: fetch -o - https://tinyurl.com/44yzxsz8 | sh -s

beta UniFi Network Application 7.4.140
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-4-140/7ca7417e-1893-482b-86c3-044c2382967f)
Install command: fetch -o - https://tinyurl.com/5euc9c6p | sh -s
NOTE: This release will only appear on UniFi OS Consoles running version 3.0 or newer, it's not recommended for consoles running older UniFi OS versions.

beta UniFi Network Application 7.3.83
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-3-83/9c5f3dc2-b64d-42dc-86de-caef9c40d60f)
Install command: fetch -o - https://tinyurl.com/485sxuyr | sh -s

RC UniFi Network Application 7.3.81
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-3-81/5a425a85-88d4-4d6a-aed2-623e774b3314)
Install command: fetch -o - https://tinyurl.com/3fzkkxz6 | sh -s
NOTE: just moved up jbigkit above tiff app

beta UniFi Network Application 7.3.80
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-3-80/279d5a76-ab2f-43b3-be64-2cdfc2c24c15)
Install command: fetch -o - https://tinyurl.com/3pmz4yfn | sh -s

beta UniFi Network Application 7.3.76
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-3-76/6d70a679-da11-4f38-af0b-d87ade82395e)
Install command: fetch -o - https://tinyurl.com/bdec9by6 | sh -s

beta UniFi Network Application 7.3.73
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-3-73/c7c02a9e-584a-4a23-a72c-9709cdff955c)
Install command: fetch -o - https://tinyurl.com/4fxzjrb5 | sh -s

beta UniFiNetworkApplication 7.3.69
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-3-69/d801e00a-8d7d-4e52-b6db-d4d8d87835fb)
** Support for the UC-CK has been dropped in UniFi Network 7.3 and newer. ([vintage product](https://help.ui.com/hc/en-us/articles/1500001268521))
using OpenJDK11
Install command: fetch -o - https://tinyurl.com/2kbdcpm4 | sh -s

beta UniFiNetworkApplication 7.2.94
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-2-94/b559f699-407f-44bb-a6dc-f95ade25c1ff)
Install command: fetch -o - https://tinyurl.com/yc4rbrtw | sh -s

beta UniFiNetworkApplication 7.2.93
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-2-93/7ae66066-72d0-4336-8400-e89d951ef11d)
Install command: fetch -o - https://tinyurl.com/23yw92tk | sh -s

beta UniFiNetworkApplication 7.2.91
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-2-91/6f078b6c-8665-41f4-83f1-07069667805d)
Install command: fetch -o - https://tinyurl.com/3jpwp2wj | sh -s

beta UniFiNetworkApplication 7.2.88
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-2-88/43ea8429-552f-42d0-800f-3f7dc1ae43df)
Install command: fetch -o - https://tinyurl.com/3hw9mhxw | sh -s

install at your own risk, back up your DB first

with merged: 
Fry-kun's (MongoDB42, remover for old MongoDB)
shaneallgeier (use of pkg instead of txz)

### CODE REVIEW

**Comment by tong2x** [comment]
error when running.... beta UniFiNetworkApplication 7.3.69

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ubnt/ace/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by tong2x** [comment]
beta UniFiNetworkApplication 7.3.69
with OpenJDK11
Install command: fetch -o - https://tinyurl.com/2kbdcpm4 | sh -s

it is now running in may test machine
OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
Intel(R) Celeron(R) CPU 1037U @ 1.80GHz (2 cores, 2 threads)

Minor non fatal error at end of installation
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/local/UniFi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by tong2x** [comment]
added, by [shawnma](https://github.com/shawnma)
Quit the installation process if one of the package failed to install. #299

**Comment by vtermaat** [comment]
https://github.com/unofficial-unifi/unifi-pfsense/issues/302

**Comment by hacesoft** [comment]
After updating pfsense to version 23.01 and then installing UniFi Network Application of different versions such as:
7.4.144
7.4.140
7.3.83

Installation always ends with an error:

Is there any solution?

  WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
         at com.ubnt.service.system.o0oOo.<clinit>(Unknown Source)
         at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo
         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
         ... 2 more

**Comment by tong2x** [comment]
within the package installation, you dont received any error?
I do have a non fatel error at end, which is I think different than your error message, 
could you confirm if unifi doe not run?

sorry, I only have opnsense to test with

**Comment by hacesoft** [comment]
After installation, the driver really doesn't work... I tried to stop it and then start it and there was no response, or with the error message that I sent.

Now I try to install version 7.4.144 and it says during installation:

x packagesite.yamlWARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)

Package png-1.6.39 already installed.
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
         at com.ubnt.service.system.LA.<clinit>(Unknown Source)
         at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo
         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
         ... 2 more

At the end it writes another error:

  done.
Updating mongod link... done.
Checking partition size... done.
Updating snappy java...cp: /usr/local/share/java/classes/snappy-java.jar: No such file or directory
  done.
/usr/local/etc/rc.d/unifi.sh 1686 B 2971 kBps 00s
  done.
Starting the unifi service...Starting UniFi controller.
  done.

**Comment by tong2x** [comment]
as far as the package installation there are no errors? like failed to install? or locked packages?
if to quick you may want to add the following to your install script " cmd |& tee unifi74144.txt"

mine always has this errors and no error in the package install, im thingking there are errors in the package install maybe.
there is also a PR here in github who is using pfsense maybe you could check that out also if related

> Starting the unifi service...Starting UniFi controller.
>  done.
> root@OPNsense:~ # WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/local/UniFi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
> WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Starting the unifi service...Starting UniFi controller.

Unifi will still run normally sometime there will be "NOT FOUND" error in web but will be find after unifi restart or reboot of opnsense

**Comment by hacesoft** [comment]
I am sending the installation log of UniFi Driver 7.4.144 on hw PC Engines APU.4D4 with PfSense 23.01-RELEASE (amd64).

[unifi74144.txt](https://github.com/unofficial-unifi/unifi-pfsense/files/10776552/unifi74144.txt)

**Comment by tong2x** [comment]
this could be an issue with java
please try the java trouble shooting or try resintalling jdk and snappy java
i think there is also an open issue or pull with specific on java and pfsense just forget the actual link though

WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such file or directory)
Package mpdecimal-2.5.1 already installed.
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
	at com.ubnt.service.system.LA.<clinit>(Unknown Source)
	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo

**Pull request closed without merging**
