### PR TITLE
Beta UniFiNetworkApplication 7.0.15 MongoDB42

### PR DESCRIPTION
**Pull request by tong2x**
Beta UniFiNetworkApplication 7.0.15 MongoDB42
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-7-0-15/0ccbe7da-de96-4444-9362-b4d1acf3056f)

MongoDB 4.2
Install command: fetch -o - https://git.io/JyeJg | sh -s

install at your own risk, back up your DB first

### CODE REVIEW

**Comment by tong2x** [comment]
I am still having issues with mongdb42, even if I clean uninstall unifi, uninstall mongodb.
I even followed the mongodb upgrade procedure. but installing with mongodb40 is ok no problem.

issue is that after install for some reason unifi is having problems access the DB? where could Iget logs to check and see where the problem is?

**Comment by shortbloke** [comment]
@tong2x the log file is in: `/usr/local/UniFi/logs/mongod.log`

**Comment by tong2x** [comment]
the attached log should be the log for mongdb42
I delete the log file then installed the scritp with mongodb42
> 2021-12-25T12:33:06.193+0800 I CONTROL  [initandlisten] db version v4.0.27
not quite sure what to look at, but db has not update? or is that normal?
I have follow the instruction in setting the feature compatibility to 4.0

[mongod.log](https://github.com/unofficial-unifi/unifi-pfsense/files/7776544/mongod.log)

**Comment by shortbloke** [comment]
If you look at the end of the log Mongo 4.2 is being used and it looks to start up ok:
```
2021-12-25T14:19:33.110+0800 I  CONTROL  [initandlisten] MongoDB starting : pid=11504 port=27117 dbpath=/usr/local/UniFi/data/db 64-bit host=OPNsense.localdomain
2021-12-25T14:19:33.110+0800 I  CONTROL  [initandlisten] db version v4.2.17
```

and connections appear to come in from UniFi:
```
2021-12-25T14:19:33.907+0800 I  NETWORK  [listener] connection accepted from 127.0.0.1:38413 #1 (1 connection now open)
2021-12-25T14:19:33.912+0800 I  NETWORK  [conn1] received client metadata from 127.0.0.1:38413 conn1: { driver: { name: "mongo-java-driver", version: "3.4.3-dirty" }, os: { type: "unknown", name: "FreeBSD", architecture: "amd64", version: "12.1-RELEASE-p21-HBSD" }, platform: "Java/OpenJDK BSD Porting Team/1.8.0_312-b07" }
```

Is UniFi Controller not coming up, or is it showing it's upgrading the database or something?

**Comment by tong2x** [comment]
Unifi does show up and I could login, even view the devices. once I do a DB compact Unifi crashes.
I am gonna let it run for a while but not use compact and see if it crashes

attached is the new logs, and screen shot of error
[mongod.log](https://github.com/unofficial-unifi/unifi-pfsense/files/7777879/mongod.log)
Screenshot_20211226-224619_VNC Viewer
Screenshot_20211226-224259_VNC Viewer

**Pull request closed without merging**
