### PR TITLE
Official UniFi Network Application 6.5.52

### PR DESCRIPTION
**Pull request by tong2x**
Official UniFi Network Application 6.5.51
[Firmware Overview/Details](https://community.ui.com/releases/UniFi-Network-Application-6-5-52/b7ca4128-c6f7-4741-9da1-e216db190452)

Install command: fetch -o - https://git.io/J13Rm | sh -s

install at your own risk, back up your DB first

### CODE REVIEW

**Comment by hacesoft** [comment]
I have installed this version and it takes a lot of system resources. Unusable ... I went back to version: 6.5.51.

**Comment by tong2x** [comment]
thank you for the info

having trouble as well also with 53...

**Comment by alexw1982** [comment]
Since .53 has been merged - is it now stable or do you guys still see bugs / stability/ performance issues?

**Comment by tong2x** [comment]
my trouble seems to be hardware related... I have since formated my opnsense  and even installed older firmware and seem to have issue with "restoring" backup... when I do unifi breaks.

i did install 53 on other opnsense hardware and it is ok, and have upgraded my gen1 key controller and it is fine.

**Comment by alexw1982** [comment]
Ok, thanks - will give it a try …

**Pull request closed without merging**
