### PR TITLE
Official Unifi Network Application 7.2.92

### PR DESCRIPTION
**Pull request by tong2x**
Official Unifi Network Application 7.2.92
PR #295
[Details/Descriptions](https://community.ui.com/releases/UniFi-Network-Application-7-2-92/f1903cbc-4daa-4695-ac8c-7324bcff529a)
Install command: fetch -o - https://tinyurl.com/vcesck68 | sh -s

Official Unifi Network Application 7.1.66
[Details/Descriptions](https://community.ui.com/releases/UniFi-Network-Application-7-1-66/cf1208d2-3898-418c-b841-699e7b773fd4)
Install command: fetch -o - https://tinyurl.com/4vyv57zb | sh -s

always backup you DB just in casse

### CODE REVIEW

**Comment by clunesy** [comment]
Hi there - I'm a noob here. Do you know when this will be updated? I've tried to manually edit the install-unifi.sh file to the path for version 7.1.66 and run the script locally on FreeBSD but it doesn't work.

**Comment by tong2x** [comment]
hello @clunesy this will be added when pears have reviewed it or more than 3 months have pass. I have however made edit to include an install script if you would like to install it now, rather than later.

**Comment by clunesy** [comment]
This is great - much appreciated.

**Comment by tong2x** [comment]
official firmware added to base via other pull

**Pull request closed without merging**
